### ISSUE TITLE
undefined constant error when loading an extension

### ISSUE THREAD

**Issue by jsierles** [exponentjs/rem#4]
I've prepared a repository for rem, but it issues an error that *NativeModules.CameraManager.Aspect* is undefined.

NativeModules.CameraManager.Aspect

https://github.com/jsierles/react-native-camera

**Comment by mikeljames** [comment]
Hi @jsierles Did you fix this? I've been getting the same error on react-native-camera plugin

**Comment by jsierles** [comment]
Nope, just left this and haven't touched in a while, sorry.

**Comment by mikeljames** [comment]
Hey, I've since made progress, turns out I hadn't followed the install steps correctly.

**Comment by tomprogers** [comment]
@export-mike Can you elaborate on how you got it to work? I'm also trying to use react-native-camera, and I'm getting this same error.

**Comment by export-mike** [comment]
@tomprogers I hadn't gone through the steps fully in: https://github.com/jsierles/react-native-camera#getting-started
